#!/bin/sh
servers_readable=$HOME"/creds/servers.conf.readable"
servers=$HOME"/creds/servers.conf"
servers_tmp=$HOME"/creds/servers.conf.tmp"

serverList=`cat "${servers_readable}"`

if [ -e "${servers_tmp}" ]; then
    rm "${servers_tmp}"
fi;

for server in $serverList
do
    printf "%05d %s\n" "$RANDOM" "${server}" >> "${servers_tmp}"
done

sort -n "${servers_tmp}" | cut -c7- > "${servers}"

rm "${servers_tmp}"

encryptedServers=$HOME"/openwrt-ss-configs/shadowsocks/etc/servers.en.txt"
update_cc=$HOME"/openwrt-ss-configs/update-cc"

gpg --batch --yes --recipient unisko@gmail.com --output $encryptedServers --encrypt $servers

eval "$update_cc"
