#!/bin/sh
servers="/home/peng/creds/servers.conf"
encryptedServers="/home/peng/openwrt-ss-configs/shadowsocks/etc/servers.en.txt"
update_cc="/home/peng/openwrt-ss-configs/update-cc"

gpg --batch --yes --recipient unisko@gmail.com --output $encryptedServers --encrypt $servers

eval "$update_cc"
