#!/bin/sh
updateFlag=0
TRIES=4
localBaseDir="/home/peng/openwrt-ss-configs/"

update_remote_files () {
    localDir=$localBaseDir"shadowsocks/etc/dnsmasq.d/"

    remoteDir="https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/"
    remoteFiles="accelerated-domains.china.conf bogus-nxdomain.china.conf"

    for file in $remoteFiles
    do
        targetFile=$localDir$file
        targetFileCompressed=$file".tar.gz"
        tmpFile="/tmp/"$file".tmp"
        remoteFileUrl=$remoteDir$file

        file_fetched=0
        get_remote_files_tries=0

        until [ $file_fetched -eq 1 ] || [ $get_remote_files_tries -gt $TRIES ]
        do
            wget -4 --no-check-certificate -O $tmpFile $remoteFileUrl 
            if [ $? -eq 0 ]; then
                file_fetched=1

                if [ -e $targetFile ]; then
                    oldMd5sum=`md5sum $targetFile | awk '{print substr($1,1)}'`
                    newMd5sum=`md5sum $tmpFile | awk '{print substr($1,1)}'`

                    if [ $newMd5sum = $oldMd5sum ]; then
                        :
                    else
                        mv $tmpFile $targetFile
                        updateFlag=1
                    fi;
                else
                    mv $tmpFile $targetFile
                    updateFlag=1
                fi;
            fi;                                                                        
            get_remote_files_tries=$((get_remote_files_tries+1))
        done;
    done;

    localDir=$localBaseDir"shadowsocks/etc/"
    dataUrl="http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest"
    file="chinadns_chnroute.txt"
    targetFile=$localDir$file
    targetFileCompressed=$file".tar.gz"
    tmpFile="/tmp/"`echo $targetFile | awk '{sub(/.*\//,x)}'1`".tmp"

    file_fetched=0
    get_remote_files_tries=0

    until [ $file_fetched -eq 1 ] || [ $get_remote_files_tries -gt $TRIES ]
    do 
        wget -O- $dataUrl | awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > $tmpFile

        if [ $? -eq 0 ]; then
            cd $localDir
            file_fetched=1

            if [ -e targetFile ]; then
                oldMd5sum=`md5sum $targetFile | awk '{print substr($1,1)}'`
                newMd5sum=`md5sum $tmpFile | awk '{print substr($1,1)}'`

                if [ $newMd5sum = $oldMd5sum ]; then
                    :
                else
                    mv $tmpFile $targetFile
                    /bin/tar -czf $targetFileCompressed $file
                    updateFlag=1
                fi;
            else
                mv $tmpFile $targetFile
                /bin/tar -czf $targetFileCompressed $file
                updateFlag=1
            fi;
        fi;
        get_remote_files_tries=$((get_remote_files_tries+1))
    done;
}


update_remote_files

if [ $updateFlag -eq 1 ]; then
    cd $localBaseDir
    eval $localBaseDir"update-cc"
else
    exit 0;
fi;

