#!/bin/sh /etc/rc.common

# Author: https://github.com/gnu4cn/openwrt-ss-configs
# Date: 2016-10

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
    sed -i 's/114.114.114.114/127.0.0.1#3210/' /etc/dnsmasq.d/gfwlist.conf
    /etc/init.d/dnsmasq restart

    servers=`cat /etc/servers.conf`
    servers_tmp="/tmp/servers.conf.tmp"
    servers_random="/etc/servers.used"    

    count=0    
    SERVERS_FOR_DNS=3
    XFOSSDOTCOM="52.187.134.153"
    count_tun=0

    if [ -e "${servers_tmp}" ]; then
        rm "${servers_tmp}"
    fi;

    if [ -e "${servers_random}" ]; then
        rm "${servers_random}"
    fi;

    for s in $servers;
    do
        printf "%05d %s\n" "`tr -cd 1-9 < /dev/urandom | head -c 5`" "${s}" >> "${servers_tmp}"
    done

    sort -n "${servers_tmp}" | cut -c7- > "${servers_random}"

    rm "${servers_tmp}"

    serverList=`cat "${servers_random}"`

    for server in $serverList
    do
    	#n=`tr -cd 0-9 < /dev/urandom | head -c 1`

        addr=`echo $server|awk '{split($0,a,":"); print a[1];}'`;
        port=`echo $server|awk '{split($0,a,":"); print a[2];}'`;
        cred=`echo $server|awk '{split($0,a,":"); print a[3];}'`;
        
        service_start /usr/bin/ss-redir -s "${addr}" -p "${port}" -k "${cred}" -u -b 0.0.0.0 -m rc4-md5 -l 7654 -t 600 -f /var/run/ss-redir.${count}.pid

        if [ $count_tun -lt $SERVERS_FOR_DNS ] && [ "$addr" = "$XFOSSDOTCOM" ]; then
            service_start /usr/bin/ss-tunnel -s "${addr}" -p "${port}" -k "${cred}" -u -b 0.0.0.0 -m rc4-md5 -t 600 -l 3210 -L 8.8.8.8:53 -f /var/run/ss-tunnel.${count_tun}.pid
            count_tun=$((count_tun+1))
        fi;

        count=$((count+1))
    done;

    /usr/bin/shadowsocks-firewall
}

stop() {
	sed -i 's/127.0.0.1#3210/114.114.114.114/' /etc/dnsmasq.d/gfwlist.conf
	/etc/init.d/dnsmasq restart

	service_stop /usr/bin/ss-redir
	service_stop /usr/bin/ss-tunnel
	killall ss-redir
	killall ss-tunnel
	/etc/init.d/firewall restart
}
