#!/bin/sh /etc/rc.common

# Author: https://github.com/gnu4cn/openwrt-ss-configs
# Date: 2016-10

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
    sed -i 's/114.114.114.114/127.0.0.1#3210/' /etc/dnsmasq.d/gfwlist.conf
    /etc/init.d/dnsmasq restart

    servers=`cat /etc/servers.conf`
    servers_tmp="/tmp/servers.conf.tmp"
    servers_random="/etc/servers.used"    

    count=0    
    OWN_SERVER="23.106.148.174"
    OWN_SERVER_USED=0
    additional_server_selected=0

    if [ -e "$servers_tmp" ]; then
        rm "$servers_tmp"
    fi;

    if [ -e "$servers_random" ]; then
        rm "$servers_random"
    fi;

    for s in $servers;
    do
        printf "%05d %s\n" "`tr -cd 1-9 < /dev/urandom | head -c 5`" "$s" >> "$servers_tmp"
    done

    sort -n "$servers_tmp" | cut -c7- > "$servers_random"

    rm "$servers_tmp"

    serverList=`cat "$servers_random"`

    addr_used=""

    for server in $serverList
    do
        addr=`echo $server|awk -F '[:]'  '{printf $1}'`;
        port=`echo $server|awk -F '[:]'  '{printf $2}'`;
        cred=`echo $server|awk -F '[:]'  '{printf $3}'`;
        
        find_addr=`echo "$addr_used" | grep "$addr"`
        if test -z "$find_addr"; then 
            service_start /usr/bin/ss-redir -s "${addr}" -p "${port}" -k "${cred}" -u -b 0.0.0.0 -m rc4-md5 -l 7654 -t 600 -f /var/run/ss-redir."$count".pid
            if [ $count -eq 0 ]; then
                addr_used="$addr_used""$addr"
            else
                addr_used="$addr_used"" $addr"
            fi;
        fi;

        if [ "$addr" = "$OWN_SERVER" ] && [ $OWN_SERVER_USED -eq 0 ]; then
            service_start /usr/bin/ss-tunnel -s "${addr}" -p "${port}" -k "${cred}" -u -b 0.0.0.0 -m rc4-md5 -t 600 -l 3210 -L 8.8.8.8:53 -f /var/run/ss-tunnel."$count".pid
            OWN_SERVER_USED=1
        fi;

        if [ "$addr" != "$OWN_SERVER" ] && [ $additional_server_selected -eq 0 ]; then
            service_start /usr/bin/ss-tunnel -s "${addr}" -p "${port}" -k "${cred}" -u -b 0.0.0.0 -m rc4-md5 -t 600 -l 3210 -L 8.8.8.8:53 -f /var/run/ss-tunnel."$count".pid
            additional_server_selected=1
        fi;

        count=$((count+1))
    done;

    /usr/bin/shadowsocks-firewall
}

stop() {
	sed -i 's/127.0.0.1#3210/114.114.114.114/' /etc/dnsmasq.d/gfwlist.conf
	/etc/init.d/dnsmasq restart

	service_stop /usr/bin/ss-redir
	service_stop /usr/bin/ss-tunnel
	killall ss-redir
	killall ss-tunnel
	/etc/init.d/firewall restart
}
