#!/bin/sh /etc/rc.common

# Author: https://github.com/softwaredownload/openwrt-fanqiang
# Date: 2015-12 

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
    sed -i 's/114.114.114.114/127.0.0.1#3210/' /etc/dnsmasq.d/gfwlist.conf
    /etc/init.d/dnsmasq restart

    servers=`cat /etc/servers.conf`;

    count=0    
    SERVERS_FOR_DNS=8
    count_tun=0

    for server in $servers;
    do
    	n=`tr -cd 0-9 < /dev/urandom | head -c 1`

        addr=`echo $server|awk '{split($0,a,":"); print a[1];}'`;
        port=`echo $server|awk '{split($0,a,":"); print a[2];}'`;
        cred=`echo $server|awk '{split($0,a,":"); print a[3];}'`;
        service_start /usr/bin/ss-redir -u -b 0.0.0.0 -s $addr -p $port -k $cred -m rc4-md5 -l 7654 -t 600 -f /var/run/ss-redir.$count.pid

        if [ $count_tun -lt $SERVERS_FOR_DNS ] && [ `expr $n % 2` -eq 1 ]; then
            service_start /usr/bin/ss-tunnel -b 0.0.0.0 -s $addr -p $port -k $cred -m rc4-md5 -t 600 -l 3210 -L 8.8.8.8:53 -u -f /var/run/ss-tunnel.$count_tun.pid
            count_tun=$((count_tun+1))
        fi;

        count=$((count+1))
    done;

    /usr/bin/shadowsocks-firewall
}

stop() {
	sed -i 's/127.0.0.1#3210/114.114.114.114/' /etc/dnsmasq.d/gfwlist.conf
	/etc/init.d/dnsmasq restart

	service_stop /usr/bin/ss-redir
	service_stop /usr/bin/ss-tunnel
	killall ss-redir
	killall ss-tunnel
	/etc/init.d/firewall restart
}
